version: '3.4'

services:
  db:
    image: projeto_inventro_db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER : docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE : CTI_TESTE04
    ports:
     - 3308:3306
    networks: 
     - SESC_TI

  projeto_inventro:
    image: projetoinventro
    build:
      context: .
      dockerfile: Projeto_Inventáro/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks: 
    - SESC_TI

networks:
  SESC_TI:
   driver: bridge


